[package]
name = "gmbr"
version = "0.1.0"
authors = ["aleixsanchis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
config = "0.10.1"
serde_json = "1.0"
hex = "0.4.0"
sfml = "0.15.1"
bit_field = "0.9.0"
